language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - sudo apt-get install -y libevent-dev python-gevent
install:
    - pip install -r test-requirements.txt --use-mirrors
    - python setup.py develop
script: unit2 discover -v && flake8 circusweb
notifications:
    email: tarek@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change
